[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/*.otf"
  to = "/:splat"
  status = 200
  force = true
  headers = { Content-Type = "font/opentype" }

[[redirects]]
  from = "/*.ttf"
  to = "/:splat"
  status = 200
  force = true
  headers = { Content-Type = "font/truetype" }

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = true
  headers = { Content-Type = "font/:splat" }